---
- hosts: projectname_devuan_Role_composer
  gather_facts: false
  tasks:
    - name: Install/upgrade composer
      get_url:
        # https://getcomposer.org/download/
        url: https://getcomposer.org/download/1.8.6/composer.phar
        checksum: "sha256:b66f9b53db72c5117408defe8a1e00515fe749e97ce1b0ae8bdaa6a5a43dd542"
        dest: /usr/local/bin/composer
        owner: root
        mode: '0755'
