---
- hosts: projectname_devuan_Role_webserver-php72
  gather_facts: false
  tasks:
    # https://www.rosehosting.com/blog/how-to-install-php-7-2-on-debian-9/
    - name: Add apt key for newer PHP packages
      apt_key:
        id: 15058500A0235D97F5D10063B188E2B695BD4743
        url: https://packages.sury.org/php/apt.gpg
        state: present

    - name: Install packages for apt over https
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apt-transport-https
          - ca-certificates

    # From https://docs.ansible.com/ansible/latest/modules/apt_key_module.html:
    # > Adding a new key requires an apt cache update (e.g. using the apt
    # > module’s update_cache option)
    # This satisfies this requirement because 'update_cache' is true by default.
    - name: Add apt repository for newer PHP packages
      apt_repository:
        repo: "deb https://packages.sury.org/php/ stretch main"
        state: present

    - name: Install PHP 7.2 packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apache2
          - libapache2-mod-php7.2
          - php7.2-curl
          - php7.2-imagick
          - php7.2-mbstring
          - php7.2-mysql
          - php7.2-xml
      register: result_install_php72

    - name: Restart Apache if any new packages installed
      command: "/etc/init.d/apache2 restart"
      when: result_install_php72['changed']
